version: '3.6'

services:
  db:
    container_name: postgres
    image: postgres:9.6
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: always
    networks:
      - nestjs-networks
  
  app:
    container_name: app
    build: .
    command: npm run start:prod
    env_file:
      - .env.development
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - nestjs-networks

networks:
  nestjs-networks: